const dares = [
    "Hand your phone, unlocked, to the person on your left for 60 seconds — no deleting anything first.",
    "Let the group scroll through your camera roll for 30 seconds.",
    "Do your best impression of the person sitting next to you.",
    "Do your best impression of the person you find most intimidating in the room.",
    "Sing a love song to the person across from you, full eye contact required.",
    "Hold a plank for 30 seconds — if you drop early, answer any question truthfully.",
    "Hold eye contact with the person on your right for 30 seconds without laughing.",
    "Let someone else send one text from your phone to anyone in your contacts (they show you before sending).",
    "Give the person to your left a genuine compliment you've never told them.",
    "Text your crush (or last crush) something the group decides — you can veto once.",
    "Let the group pick your phone background for the next hour.",
    "Read out loud the last text conversation you had, word for word (skip anything private).",
    "Call the last person you texted and tell them you miss them, then hang up without explaining.",
    "Let the person closest to you go through your recent call log and ask about one name.",
    "Do your best slow-dance with the nearest empty chair for 15 seconds.",
    "Give the person across from you a piggyback ride around the room.",
    "Let the group pick one contact in your phone for you to voice-message right now, saying only 'thinking of you.'",
    "Whisper something you find attractive about the person of your choice in the room.",
    "Hold hands with the person next to you until your next turn.",
    "Give your phone passcode to the group for the next five minutes.",
    "Let someone else pick your next Instagram/TikTok post caption and you have to post it.",
    "Do your best impression of how the person to your left flirts.",
    "Send a voice note singing happy birthday to someone, even if it isn't their birthday.",
    "Let the group ask your phone's search history one question.",
    "Sit as close as possible to the person you're most attracted to in the room for the next two rounds.",
    "Let the person to your right pick your next profile picture — no veto.",
    "Show the group the last photo in your camera roll.",
    "Do your best impression of the last person who had a crush on you.",
    "Let the group choose someone for you to give a 10-second shoulder massage to.",
    "Whisper your most attractive quality directly to the person sitting next to you.",
    "Read your last five text messages out loud, no skipping.",
    "Let the person across from you scroll your DMs for 15 seconds.",
    "Do your best impression of someone in the group falling for another person in the group.",
    "Let someone else write your dating app bio right now, using your actual phone.",
    "Tell the group who in the room you'd want to be stuck in an elevator with, and why.",
    "Let the group pick who you have to compliment using only physical attraction words.",
    "Do your best impression of your last ex.",
    "Give a genuine 20-second hug to the person you've talked to the least tonight.",
    "Let the person to your right post any status of their choice from your account for one minute.",
    "Sing the chorus of a love song directly to whoever the group points at.",
    "Show the group your most recent screenshot.",
    "Let the group choose one person for you to hold hands with while answering the next question.",
    "Do your best impression of the group's reaction if you started dating the person on your right.",
    "Let someone else text 'I need to tell you something' to a random contact in your phone (you follow up after with something harmless).",
    "Trade phones with the person across from you for two full minutes.",
    "Give the person you find most charming in the room a genuine, non-joking compliment.",
    "Let the group choose your next selfie pose and post it to your story.",
    "Let the person to your left rename your contact in their phone.",
    "Give your Notes app to the person across from you to read for 20 seconds.",
    "Let the group pick a song to slow dance to with the person closest to you.",
    "Whisper the name of the person here you'd date if you were single, into the ear of the person who dared you.",
    "Let the person on your right go through your last three saved photos.",
    "Do your best impression of how the person across from you texts.",
    "Send a message to a group chat saying only '👀' and don't explain when people ask.",
    "Let the group pick a nickname for the person you're closest to here, and use it for the rest of the night.",
    "Sit on the floor next to your crush (or whoever the group picks) for the next round.",
    "Whisper one thing you find attractive about the person sitting across from you.",
    "Let someone else follow one account of their choice from your phone.",
    "Give a 15-second compliment speech about the person who dared you, no jokes allowed.",
    "Let the group choose a picture from your camera roll to be your contact photo for someone specific.",
    "Send the last person you texted a voice message singing any song for 10 seconds."
];