//num of players
//person this blah blah
//aim to discuss question 
//roulette mode where everyone answers the same question

const data = {
  "levels": [
    {
      "Level": 1,
      "LevelName": "Peripheral / Surface",
      "Questions": [
        { "QuestionID": "L1Q1", "Question": "What genre or artist have you listened to the most in the past month?" },
        { "QuestionID": "L1Q2", "Question": "What did you do this past weekend, and was it typical for you?" },
        { "QuestionID": "L1Q3", "Question": "What is your favorite food, and what is the specific memory of when you first tried it?" },
        { "QuestionID": "L1Q4", "Question": "What movie or TV show have you recommended to the most people, and why?" },
        { "QuestionID": "L1Q5", "Question": "If you had to move tomorrow, would you pick a city apartment or a countryside house, and why?" },
        { "QuestionID": "L1Q6", "Question": "What sport or physical activity do you currently do, and how old were you the first time you tried it?" },
        { "QuestionID": "L1Q7", "Question": "What time do you naturally wake up and fall asleep when you have no alarm or obligations?" },
        { "QuestionID": "L1Q8", "Question": "If your current music taste had to be summed up in one song, which song would you pick and why that one?" },
        { "QuestionID": "L1Q9", "Question": "What is the one meal you have eaten the most times in your life without getting tired of it?" },
        { "QuestionID": "L1Q10", "Question": "What movie or show have you rewatched more than three times, and what pulls you back to it?" },
        { "QuestionID": "L1Q11", "Question": "What is the last thing you bought for yourself that you were genuinely excited about, and when did you buy it?" },
        { "QuestionID": "L1Q12", "Question": "If next Saturday had zero obligations, what would your actual hour-by-hour plan look like?" },
        { "QuestionID": "L1Q13", "Question": "What hobby or interest do you have that fewer than three people in your life know about?" },
        { "QuestionID": "L1Q14", "Question": "Which app do you open the most out of habit, and roughly how many times a day?" }
      ]
    },
    {
      "Level": 2,
      "LevelName": "Outer Layer",
      "Questions": [
        { "QuestionID": "L2Q1", "Question": "What is your current job title/role, and on a scale of 1-10 how much do you enjoy it?" },
        { "QuestionID": "L2Q2", "Question": "What specific traits do the people you enjoy spending time with usually have in common?" },
        { "QuestionID": "L2Q3", "Question": "Describe your perfect day from the moment you wake up to the moment you fall asleep." },
        { "QuestionID": "L2Q4", "Question": "What single achievement in the last five years are you most proud of?" },
        { "QuestionID": "L2Q5", "Question": "What is the last specific situation that stressed you out, and what did you actually do about it?" },
        { "QuestionID": "L2Q6", "Question": "What skill or subject are you actively learning right now, and what prompted you to start?" },
        { "QuestionID": "L2Q7", "Question": "How many countries have you traveled to, and which specific place is at the top of your list to visit next?" },
        { "QuestionID": "L2Q8", "Question": "What single task in your job or daily routine drains you the most, and how often does it come up?" },
        { "QuestionID": "L2Q9", "Question": "Is there a specific friendship that faded that you still think about — what was that person's name or role in your life?" },
        { "QuestionID": "L2Q10", "Question": "What is one skill you have that your coworkers or friends have never acknowledged or noticed?" },
        { "QuestionID": "L2Q11", "Question": "Think of the last time something went wrong for you — did you talk to someone or go quiet, and how did that choice play out?" },
        { "QuestionID": "L2Q12", "Question": "What specific goal have you been putting off for over a year, and what exact obstacle is stopping you from starting?" },
        { "QuestionID": "L2Q13", "Question": "What is the most spontaneous decision you've made in the last two years, and do you regret it?" },
        { "QuestionID": "L2Q14", "Question": "What specific type of social situation drains your energy the fastest, and how long can you last in it before needing to leave?" }
      ]
    },
    {
      "Level": 3,
      "LevelName": "Middle Layer",
      "Questions": [
        { "QuestionID": "L3Q1", "Question": "What is the single most important goal you want to achieve in the next five years?" },
        { "QuestionID": "L3Q2", "Question": "Name the top three values you try to live by, and give an example of when you acted on one." },
        { "QuestionID": "L3Q3", "Question": "What specific aspect of your childhood or upbringing had the biggest impact on who you are today?" },
        { "QuestionID": "L3Q4", "Question": "If you had to define 'success' for your own life in one sentence, what would it say?" },
        { "QuestionID": "L3Q5", "Question": "What is the hardest decision you've made in the last two years, and what made it so difficult?" },
        { "QuestionID": "L3Q6", "Question": "How would you describe your relationship with each of your immediate family members right now?" },
        { "QuestionID": "L3Q7", "Question": "What specific belief do you hold that most people close to you would disagree with if you said it out loud?" },
        { "QuestionID": "L3Q8", "Question": "What is one specific thing a parent did that you swore you'd never repeat — and have you caught yourself doing it recently?" },
        { "QuestionID": "L3Q9", "Question": "Is there a specific fork in your life (a job, city, or relationship) you almost chose that you still wonder 'what if' about?" },
        { "QuestionID": "L3Q10", "Question": "What is a specific belief you held strongly five years ago that you've since completely changed your mind on?" },
        { "QuestionID": "L3Q11", "Question": "Beyond what you'd tell others, what does feeling truly successful privately look or feel like to you?" },
        { "QuestionID": "L3Q12", "Question": "Describe a specific job, relationship, or living situation you stayed in too long — what exactly kept you from leaving sooner?" },
        { "QuestionID": "L3Q13", "Question": "What is one specific thing you need from the people closest to you that you consistently struggle to ask for directly?" },
        { "QuestionID": "L3Q14", "Question": "What specific trait of yours do people most often misread, and what's an example of that happening?" }
      ]
    },
    {
      "Level": 4,
      "LevelName": "Core Self / Innermost",
      "Questions": [
        { "QuestionID": "L4Q1", "Question": "What is the single fear or insecurity that affects your decisions most often, and when did it last show up?" },
        { "QuestionID": "L4Q2", "Question": "What is one specific thing you have never told anyone, and what has kept you from sharing it?" },
        { "QuestionID": "L4Q3", "Question": "Describe the specific moment or event that most changed how you see life, including roughly when it happened." },
        { "QuestionID": "L4Q4", "Question": "What is the one decision or action in your life you regret most, and why does it still stick with you?" },
        { "QuestionID": "L4Q5", "Question": "What specific thing feels most missing from your life right now — a person, feeling, or circumstance?" },
        { "QuestionID": "L4Q6", "Question": "Describe a specific recent moment when you felt most like your true self, and what made it feel that way." },
        { "QuestionID": "L4Q7", "Question": "What is one specific thing you'd do differently starting tomorrow if you knew no one would judge you for it?" },
        { "QuestionID": "L4Q8", "Question": "What specific fear do you know is irrational, yet it still shapes a decision you make regularly?" },
        { "QuestionID": "L4Q9", "Question": "Is there a specific past action you've never fully forgiven yourself for, and what happened?" },
        { "QuestionID": "L4Q10", "Question": "Thinking about your last close relationship that ended, what is the most honest reason it ended, beyond what you told others?" },
        { "QuestionID": "L4Q11", "Question": "What specific thing do you wish people would say about you at your funeral that no one currently says about you while you're alive?" },
        { "QuestionID": "L4Q12", "Question": "What is one specific thing you genuinely believe about yourself that you would never say out loud, even to close friends?" },
        { "QuestionID": "L4Q13", "Question": "What specific time or situation makes you feel loneliest, and is there a single person in your life who actually knows this about you?" },
        { "QuestionID": "L4Q14", "Question": "What is the one specific thing you're most afraid someone who loves you will eventually realize about you?" },
        { "QuestionID": "L4Q15", "Question": "Have you ever wanted something you knew was wrong to want — what was it, and did you ever act on it?" },
        { "QuestionID": "L4Q16", "Question": "Is there a specific person you've thought about in a way you'd never admit to them, and what stopped you from saying it?" },
        { "QuestionID": "L4Q17", "Question": "What is the closest you've ever come to being unfaithful — physically or emotionally — to someone you were committed to?" },
        { "QuestionID": "L4Q18", "Question": "What is one desire or fantasy you've never told a partner about, and why have you kept it hidden?" },
        { "QuestionID": "L4Q19", "Question": "Have you ever lied to someone's face about loving them, or about not loving someone else? What was the situation?" },
        { "QuestionID": "L4Q20", "Question": "What is the most jealous or possessive you've ever felt about someone, and what did you do — or almost do — because of it?" },
        { "QuestionID": "L4Q21", "Question": "Is there a specific line you swore you'd never cross that you eventually crossed anyway? What was it?" },
        { "QuestionID": "L4Q22", "Question": "What is the most manipulative thing you've knowingly done to get what — or who — you wanted?" },
        { "QuestionID": "L4Q23", "Question": "If your partner (past or current) could see one specific memory or thought in your head that you've hidden from them, what would it be?" },
        { "QuestionID": "L4Q24", "Question": "What is the most selfish choice you've made in a relationship, and would you make it again?" },
        { "QuestionID": "L4Q25", "Question": "What is the most painful thing a parent, sibling, or family member has ever said to you, word for word if you remember it?" },
        { "QuestionID": "L4Q26", "Question": "Is there someone still alive you need to forgive but haven't — who are they and what happened?" },
        { "QuestionID": "L4Q27", "Question": "What is a specific trauma or hard experience from your past that still affects how you act today, and how does it show up?" },
        { "QuestionID": "L4Q28", "Question": "Have you ever felt like you were pretending to be okay for so long you forgot what 'okay' actually feels like? When was that period?" },
        { "QuestionID": "L4Q29", "Question": "What is the cruelest thing you've ever said or done to someone you loved, and have you ever apologized for it?" },
        { "QuestionID": "L4Q30", "Question": "Is there a version of yourself from a few years ago you feel ashamed of? What did that version of you do?" },
        { "QuestionID": "L4Q31", "Question": "What is something about your body, mind, or life that you privately struggle to accept about yourself?" },
        { "QuestionID": "L4Q32", "Question": "Have you ever felt suicidal, or so low you didn't want to exist anymore? What got you through it, if you're comfortable sharing?" },
        { "QuestionID": "L4Q33", "Question": "What is the biggest secret someone in your family has kept, and how did discovering it (or keeping it) affect you?" },
        { "QuestionID": "L4Q34", "Question": "Who is the person you've hurt the most in your life, and have you ever told them how sorry you are?" },
        { "QuestionID": "L4Q35", "Question": "What is a specific childhood memory that still makes you emotional to think about, and why does it stay with you?" },
        { "QuestionID": "L4Q36", "Question": "Do you believe you are truly loved by the people closest to you right now, or do you secretly doubt it? What makes you feel that way?" },
        { "QuestionID": "L4Q1", "Question": "What is the single fear or insecurity that affects your decisions most often, and when did it last show up?" },
        { "QuestionID": "L4Q2", "Question": "What is one specific thing you have never told anyone, and what has kept you from sharing it?" },
        { "QuestionID": "L4Q3", "Question": "Describe the specific moment or event that most changed how you see life, including roughly when it happened." },
        { "QuestionID": "L4Q4", "Question": "What is the one decision or action in your life you regret most, and why does it still stick with you?" },
        { "QuestionID": "L4Q5", "Question": "What specific thing feels most missing from your life right now — a person, feeling, or circumstance?" },
        { "QuestionID": "L4Q6", "Question": "Describe a specific recent moment when you felt most like your true self, and what made it feel that way." },
        { "QuestionID": "L4Q7", "Question": "What is one specific thing you'd do differently starting tomorrow if you knew no one would judge you for it?" },
        { "QuestionID": "L4Q8", "Question": "What specific fear do you know is irrational, yet it still shapes a decision you make regularly?" },
        { "QuestionID": "L4Q9", "Question": "Is there a specific past action you've never fully forgiven yourself for, and what happened?" },
        { "QuestionID": "L4Q10", "Question": "Thinking about your last close relationship that ended, what is the most honest reason it ended, beyond what you told others?" },
        { "QuestionID": "L4Q11", "Question": "What specific thing do you wish people would say about you at your funeral that no one currently says about you while you're alive?" },
        { "QuestionID": "L4Q12", "Question": "What is one specific thing you genuinely believe about yourself that you would never say out loud, even to close friends?" },
        { "QuestionID": "L4Q13", "Question": "What specific time or situation makes you feel loneliest, and is there a single person in your life who actually knows this about you?" },
        { "QuestionID": "L4Q14", "Question": "What is the one specific thing you're most afraid someone who loves you will eventually realize about you?" },
        { "QuestionID": "L4Q15", "Question": "Have you ever wanted something you knew was wrong to want — what was it, and did you ever act on it?" },
        { "QuestionID": "L4Q16", "Question": "Is there a specific person you've thought about in a way you'd never admit to them, and what stopped you from saying it?" },
        { "QuestionID": "L4Q17", "Question": "What is the closest you've ever come to being unfaithful — physically or emotionally — to someone you were committed to?" },
        { "QuestionID": "L4Q18", "Question": "What is one desire or fantasy you've never told a partner about, and why have you kept it hidden?" },
        { "QuestionID": "L4Q19", "Question": "Have you ever lied to someone's face about loving them, or about not loving someone else? What was the situation?" },
        { "QuestionID": "L4Q20", "Question": "What is the most jealous or possessive you've ever felt about someone, and what did you do — or almost do — because of it?" },
        { "QuestionID": "L4Q21", "Question": "Is there a specific line you swore you'd never cross that you eventually crossed anyway? What was it?" },
        { "QuestionID": "L4Q22", "Question": "What is the most manipulative thing you've knowingly done to get what — or who — you wanted?" },
        { "QuestionID": "L4Q23", "Question": "If your partner (past or current) could see one specific memory or thought in your head that you've hidden from them, what would it be?" },
        { "QuestionID": "L4Q24", "Question": "What is the most selfish choice you've made in a relationship, and would you make it again?" },
        { "QuestionID": "L4Q25", "Question": "What is the most painful thing a parent, sibling, or family member has ever said to you, word for word if you remember it?" },
        { "QuestionID": "L4Q26", "Question": "Is there someone still alive you need to forgive but haven't — who are they and what happened?" },
        { "QuestionID": "L4Q27", "Question": "What is a specific trauma or hard experience from your past that still affects how you act today, and how does it show up?" },
        { "QuestionID": "L4Q28", "Question": "Have you ever felt like you were pretending to be okay for so long you forgot what 'okay' actually feels like? When was that period?" },
        { "QuestionID": "L4Q29", "Question": "What is the cruelest thing you've ever said or done to someone you loved, and have you ever apologized for it?" },
        { "QuestionID": "L4Q30", "Question": "Is there a version of yourself from a few years ago you feel ashamed of? What did that version of you do?" },
        { "QuestionID": "L4Q31", "Question": "What is something about your body, mind, or life that you privately struggle to accept about yourself?" },
        { "QuestionID": "L4Q32", "Question": "Have you ever felt suicidal, or so low you didn't want to exist anymore? What got you through it, if you're comfortable sharing?" },
        { "QuestionID": "L4Q33", "Question": "What is the biggest secret someone in your family has kept, and how did discovering it (or keeping it) affect you?" },
        { "QuestionID": "L4Q34", "Question": "Who is the person you've hurt the most in your life, and have you ever told them how sorry you are?" },
        { "QuestionID": "L4Q35", "Question": "What is a specific childhood memory that still makes you emotional to think about, and why does it stay with you?" },
        { "QuestionID": "L4Q36", "Question": "Do you believe you are truly loved by the people closest to you right now, or do you secretly doubt it? What makes you feel that way?" },
        { "QuestionID": "L4Q37", "Question": "What is the first thing you noticed about the person on your left?" },
        { "QuestionID": "L4Q38", "Question": "What is one honest assumption you made about the person on your left when you first met them?" },
        { "QuestionID": "L4Q39", "Question": "What is something you genuinely like about the person on your left but have never told them?" },
        { "QuestionID": "L4Q40", "Question": "What is one thing about the person on your left that you find difficult to understand?" },
        { "QuestionID": "L4Q41", "Question": "Would you trust the person on your left with a serious secret? Why or why not?" },
        { "QuestionID": "L4Q42", "Question": "Have you ever found the person on your left attractive? You may explain or pass." },
        { "QuestionID": "L4Q43", "Question": "What is the most likely reason you and the person on your left would argue?" },
        { "QuestionID": "L4Q44", "Question": "If you had to spend an entire week with one person here, who would you choose and why?" },
        { "QuestionID": "L4Q45", "Question": "Who in this group do you think understands you the best?" },
        { "QuestionID": "L4Q46", "Question": "Who in this group would you be most nervous to date, and why?" },
        { "QuestionID": "L4Q47", "Question": "Who in this group do you think is the hardest to read emotionally?" },
        { "QuestionID": "L4Q48", "Question": "Who in this group would you call first if you were in serious trouble?" },
        { "QuestionID": "L4Q49", "Question": "Who in this group do you think gives the best advice but does not follow it themselves?" },
        { "QuestionID": "L4Q50", "Question": "Who in this group do you think has changed the most since you first met them?" },
        { "QuestionID": "L4Q51", "Question": "Who in this group would you least want to see your private messages?" },
        { "QuestionID": "L4Q52", "Question": "What was the last lie you told, and who was the last person you told it to?" },
        { "QuestionID": "L4Q53", "Question": "Who was the last person you talked to, and what is something you did not tell them?" },
        { "QuestionID": "L4Q54", "Question": "What was the last conversation you had that you keep replaying in your head?" },
        { "QuestionID": "L4Q55", "Question": "Who was the last person you searched for on social media, and what made you look them up?" },
        { "QuestionID": "L4Q56", "Question": "Who was the last person you felt jealous of, and what triggered it?" },
        { "QuestionID": "L4Q57", "Question": "Who was the last person you wanted to message but decided not to?" },
        { "QuestionID": "L4Q58", "Question": "What is the last message you received that changed your mood?" },
        { "QuestionID": "L4Q59", "Question": "Who is the last person you apologized to, and were you genuinely sorry?" },
        { "QuestionID": "L4Q60", "Question": "What is something you recently said that you wish you could take back?" },
        { "QuestionID": "L4Q61", "Question": "Who is the closest person to you emotionally, and what do they know about you that most people do not?" },
        { "QuestionID": "L4Q62", "Question": "What is one secret you have kept from the person closest to you?" },
        { "QuestionID": "L4Q63", "Question": "Who knows the most embarrassing version of you?" },
        { "QuestionID": "L4Q64", "Question": "Who do you feel safest being completely honest with?" },
        { "QuestionID": "L4Q65", "Question": "Who is someone you act differently around, and why?" },
        { "QuestionID": "L4Q66", "Question": "Who do you miss but would never text first?" },
        { "QuestionID": "L4Q67", "Question": "Who do you secretly wish would reach out to you?" },
        { "QuestionID": "L4Q68", "Question": "Who is someone you pretend not to care about anymore?" },
        { "QuestionID": "L4Q69", "Question": "Who was the last person who broke your trust?" },
        { "QuestionID": "L4Q70", "Question": "Who is someone you have forgiven but still do not fully trust?" },
        { "QuestionID": "L4Q71", "Question": "If you had to reveal one truth to the person closest to you right now, what would you tell them?" },
        { "QuestionID": "L4Q72", "Question": "Which person here would you choose to kiss, if everyone involved was comfortable with it?" },
        { "QuestionID": "L4Q73", "Question": "Have you ever had feelings for someone in this room? You may name them or pass." },
        { "QuestionID": "L4Q74", "Question": "Who here would you be most tempted to text after midnight?" },
        { "QuestionID": "L4Q75", "Question": "Who here do you think would be the most dangerous person to fall for?" },
        { "QuestionID": "L4Q76", "Question": "Have you ever flirted with someone while knowing you should not have? What happened?" },
        { "QuestionID": "L4Q77", "Question": "Who was the last person who made you feel genuinely desired or attractive?" },
        { "QuestionID": "L4Q78", "Question": "What is something romantic or personal you have done that nobody here knows about?" },
        { "QuestionID": "L4Q79", "Question": "Who is the person you would most regret losing from your life?" },
        { "QuestionID": "L4Q80", "Question": "If you could hear one person's honest opinion about you, whose opinion would you choose?" }
    ]
  },
  ]
}